### ISSUE TITLE
Need Ability to Post Headers

### ISSUE THREAD

**Issue by Kumaravasanth** [jlavallee/JMeter-Rabbit-AMQP#20]
Need the ability to post headers along with the payload. Atleast a minimum of 4 Headers

**Comment by jlavallee** [comment]
You can set message headers in the Headers section on the AMQP Publisher sampler.  This was added in PR #17.

![image](https://cloud.githubusercontent.com/assets/55904/6269061/cebb6486-b805-11e4-9866-a9ebc3335392.png)
