### ISSUE TITLE
Can't get and to build the project.

### ISSUE THREAD

**Issue by HyruleanHero1988** [jlavallee/JMeter-Rabbit-AMQP#26]
When attempting to build the project, build always fails. I'm not sure how to resolve this issue. Seems to be due to the following: 

[ivy:resolve] :: problems summary ::
[ivy:resolve] :::: WARNINGS
[ivy:resolve]   problem while downloading module descriptor: http://repo1.maven.
org/maven2/com/thoughtworks/xstream/xstream/1.4.4/xstream-1.4.4.pom: invalid sha
1: expected=9e88db04254ffc7b513471405a97a5c57d732a9c computed=e00eebf36780667926
e3daf3d67d2a88422ffbef (234ms)
[ivy:resolve]           module not found: com.thoughtworks.xstream#xstream;1.4.4

[ivy:resolve]   ==== local: tried
[ivy:resolve]     C:\Users\Raymond\.ivy2\local\com.thoughtworks.xstream\xstream\
1.4.4\ivys\ivy.xml
[ivy:resolve]     -- artifact com.thoughtworks.xstream#xstream;1.4.4!xstream.jar
:
[ivy:resolve]     C:\Users\Raymond\.ivy2\local\com.thoughtworks.xstream\xstream\
1.4.4\jars\xstream.jar
[ivy:resolve]   ==== shared: tried
[ivy:resolve]     C:\Users\Raymond\.ivy2\shared\com.thoughtworks.xstream\xstream
\1.4.4\ivys\ivy.xml
[ivy:resolve]     -- artifact com.thoughtworks.xstream#xstream;1.4.4!xstream.jar
:
[ivy:resolve]     C:\Users\Raymond\.ivy2\shared\com.thoughtworks.xstream\xstream
\1.4.4\jars\xstream.jar
[ivy:resolve]   ==== public: tried
[ivy:resolve]     http://repo1.maven.org/maven2/com/thoughtworks/xstream/xstream
/1.4.4/xstream-1.4.4.pom
[ivy:resolve]           ::::::::::::::::::::::::::::::::::::::::::::::
[ivy:resolve]           ::          UNRESOLVED DEPENDENCIES         ::
[ivy:resolve]           ::::::::::::::::::::::::::::::::::::::::::::::
[ivy:resolve]           :: com.thoughtworks.xstream#xstream;1.4.4: not found
[ivy:resolve]           ::::::::::::::::::::::::::::::::::::::::::::::
[ivy:resolve]
[ivy:resolve]
[ivy:resolve] :: USE VERBOSE OR DEBUG MESSAGE LEVEL FOR MORE DETAILS

BUILD FAILED
C:\Users\Raymond\Documents\JMeter-Rabbit-AMQP-master\build.xml:55: impossible to
 resolve dependencies:

**Comment by Amy1124** [comment]
It seems that I have exactly the same problem.

**Comment by jlavallee** [comment]
I removed my ivy cache and was able to build the project no problem.

The error you show is a problem with xstream-1.4.4 on repo1.maven.org.  Presumably the issue has been fixed.  If not, it's not a problem with this project, but with the artifact on repo1.maven.org.
