### ISSUE TITLE
dependency jar not able to download while building project

### ISSUE THREAD

**Issue by gotidhavalh** [jlavallee/JMeter-Rabbit-AMQP#59]
Hello,

I am not able to build this project. Currently, http://repo1.maven.org/maven2/ url is secured so we have to use https://repo1.maven.org/maven2/ url for downloading dependency jar file. I have changed line 68 in build.xml to use https but I am still not able to build this project successfully.

Please help me.
I have attached error screenshot for more reference.

![Screenshot_130](https://user-images.githubusercontent.com/33678499/74534191-377f6180-4f59-11ea-8288-8d5b357992dd.png)

**Comment by amandvrensburg** [comment]
Hi Dhavel,

Just struggled with this myself. Ended up doing the following:

Create a ivysettings.xml file in the same directory as ivy.xml

Then put the following in the file:

<ivysettings>
    <settings defaultResolver="chain"/>
    <resolvers>
        <chain name="chain">
            <ibiblio name="central" m2compatible="true" root="https://repo1.maven.org/maven2/"/>
        </chain>
    </resolvers>
</ivysettings>

Did the job on my side.
![image](https://user-images.githubusercontent.com/5793533/74933806-7eec6e80-53ed-11ea-892d-999ec9d9a414.png)

**Comment by gotidhavalh** [comment]
Thanks for this.
